
package gui;

import java.awt.GridBagLayout;
import java.awt.GridLayout;
import java.awt.LayoutManager;
import java.awt.event.KeyEvent;
import java.awt.event.KeyListener;
import java.util.ArrayList;
import javax.swing.JLabel;
import javax.swing.JPanel;
 /*
 * @author Uday Kandpal
 */
public class List extends javax.swing.JPanel implements KeyListener {

    private int index = 0;
    private int maxIndex;
    private String getString = "";
    private Items items = new Items();
    private boolean dispose = false;

    @Override
    public void keyTyped(KeyEvent e) {
        //throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
    }

    @Override
    public void keyPressed(KeyEvent e) {
        //throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
    }

    @Override
    public void keyReleased(KeyEvent e) {
        if (e.getKeyCode() == KeyEvent.VK_ENTER) {
            getString = items.getItemsString().get(index);
            dispose = true;
            ((javax.swing.JFrame) getParent()).dispose();
        } else if (e.getKeyCode() == KeyEvent.VK_UP) {
            if (index != 0) {
                this.getComponent(index).transferFocusBackward();
                index--;
            } else {
                this.getComponent(index).transferFocus();
                index = maxIndex;
            }
        } else if (e.getKeyCode() == KeyEvent.VK_DOWN) {
            this.getComponent(index).transferFocus();
            if (index != maxIndex) {
                index++;
            } else {
                index = 0;
            }
        }
    }

    public String getStringContext() {
        return getString;
    }

    public static class Items {

        java.util.List<JPanel> list = new ArrayList();

        java.util.List<String> text = new ArrayList();

        public void addItem(String name, String ip) {
            JPanel Item = new JPanel();
            JLabel jLabel1, jLabel2;
            jLabel1 = new JLabel(name + "<" + ip + ">");
            text.add(name + "<" + ip + ">");
            javax.swing.GroupLayout ItemLayout = new javax.swing.GroupLayout(Item);
            Item.setLayout(ItemLayout);
            ItemLayout.setHorizontalGroup(
                    ItemLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, ItemLayout.createSequentialGroup()
                            .addContainerGap()
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 29, Short.MAX_VALUE)
                            .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 308, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addContainerGap())
            );
            ItemLayout.setVerticalGroup(
                    ItemLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, ItemLayout.createSequentialGroup()
                            .addContainerGap(38, Short.MAX_VALUE)
                            .addGroup(ItemLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGap(30, 30, 30))
            );
            list.add(Item);
        }

        public java.util.List<JPanel> getItems() {
            return list;
        }

        public java.util.List<String> getItemsString() {
            return text;
        }
    }

    /**
     * Creates new form List
     */
    public List() {
        initComponents();
        maxIndex = 0;
    }

    public static Items getDefaultItem() {
        return new Items();
    }

    public List(Items s) {
        initComponents();
        maxIndex = s.getItems().size();
        LayoutManager l = new GridLayout();
        ((GridLayout) l).setColumns(1);

        this.setLayout(l);
        s.getItems().stream().forEach((j) -> {
            this.add(j);
        });
        items = s;
        int n = this.getComponents().length;
        for (int i = 0; i < n - 1; i++) {
            this.getComponent(n).setFocusable(true);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        setBackground(new java.awt.Color(255, 255, 255));
        setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Suggestions", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Times New Roman", 1, 18), new java.awt.Color(0, 0, 255))); // NOI18N
        setForeground(new java.awt.Color(0, 0, 204));
        addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                formFocusLost(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 328, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 22, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents

    private void formFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_formFocusLost
        // TODO add your handling code here:
        ((javax.swing.JFrame) getParent()).dispose();
    }//GEN-LAST:event_formFocusLost


    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
}
